// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStore.Models;

#nullable disable

namespace SportsStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418151252_RefreshCatalogAndThemeCopy")]
    partial class RefreshCatalogAndThemeCopy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SportsStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Shoes",
                            Description = "Featherlight road-running shoes with breathable mesh, responsive foam, and durable outsole grip for daily mileage.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
                            Name = "Air Sprint Running Shoes",
                            Price = 3799m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 2,
                            Category = "Shoes",
                            Description = "High-cut basketball shoes with ankle lockdown, multi-court traction pattern, and impact-absorbing heel cushioning.",
                            ImageUrl = "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=900&q=80",
                            Name = "Court Pro Basketball Shoes",
                            Price = 4499m,
                            StockQuantity = 21
                        },
                        new
                        {
                            Id = 3,
                            Category = "Jerseys",
                            Description = "Official-inspired football jersey using moisture-wicking fabric and breathable side panels for hot-weather play.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
                            Name = "Metro FC Home Jersey",
                            Price = 2299m,
                            StockQuantity = 46
                        },
                        new
                        {
                            Id = 4,
                            Category = "Jerseys",
                            Description = "Game-ready basketball jersey with lightweight knit texture, quick-dry comfort, and all-day relaxed fit.",
                            ImageUrl = "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80",
                            Name = "Tigers Basketball Jersey",
                            Price = 2599m,
                            StockQuantity = 34
                        },
                        new
                        {
                            Id = 5,
                            Category = "Equipment",
                            Description = "FIFA-size style 5 football with machine-stitched panels, stable flight, and reinforced bladder for longer use.",
                            ImageUrl = "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=900&q=80",
                            Name = "Match Football",
                            Price = 1399m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 6,
                            Category = "Equipment",
                            Description = "All-surface basketball featuring deep channel grip, balanced bounce, and premium composite cover.",
                            ImageUrl = "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=900&q=80",
                            Name = "Performance Basketball",
                            Price = 1599m,
                            StockQuantity = 48
                        },
                        new
                        {
                            Id = 7,
                            Category = "Equipment",
                            Description = "Set of 20 flexible training cones with carry rack for speed drills, footwork stations, and team practice sessions.",
                            ImageUrl = "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80",
                            Name = "Training Cones Set",
                            Price = 949m,
                            StockQuantity = 62
                        },
                        new
                        {
                            Id = 8,
                            Category = "Accessories",
                            Description = "Large-capacity duffel with ventilated shoe compartment, padded shoulder strap, and water-resistant base panel.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
                            Name = "Sports Duffel Bag",
                            Price = 1999m,
                            StockQuantity = 31
                        },
                        new
                        {
                            Id = 9,
                            Category = "Accessories",
                            Description = "Double-wall insulated bottle that keeps drinks cool for training sessions, commutes, and weekend games.",
                            ImageUrl = "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=80",
                            Name = "Insulated Water Bottle",
                            Price = 749m,
                            StockQuantity = 84
                        },
                        new
                        {
                            Id = 10,
                            Category = "Accessories",
                            Description = "Pair of stretch-fit wrist sweatbands with soft absorbent cotton blend for court, gym, and running workouts.",
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80",
                            Name = "Wrist Sweatbands",
                            Price = 449m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 11,
                            Category = "Accessories",
                            Description = "Goalkeeper gloves with latex palm grip, finger support zones, and secure wrist wrap for confident saves.",
                            ImageUrl = "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80",
                            Name = "GripFit Goalkeeper Gloves",
                            Price = 1299m,
                            StockQuantity = 37
                        },
                        new
                        {
                            Id = 12,
                            Category = "Equipment",
                            Description = "Adjustable speed rope with anti-slip handles and smooth bearings for HIIT, cardio intervals, and endurance sessions.",
                            ImageUrl = "https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?auto=format&fit=crop&w=900&q=80",
                            Name = "Power Jump Rope",
                            Price = 599m,
                            StockQuantity = 76
                        },
                        new
                        {
                            Id = 13,
                            Category = "Shoes",
                            Description = "Indoor futsal shoes with non-marking outsole, close-touch upper, and quick-cut support for fast small-sided games.",
                            ImageUrl = "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=900&q=80",
                            Name = "Velocity Indoor Futsal Shoes",
                            Price = 3399m,
                            StockQuantity = 24
                        },
                        new
                        {
                            Id = 14,
                            Category = "Jerseys",
                            Description = "Quick-dry training jersey with airflow mesh zones and lightweight stretch fit for gym circuits and team drills.",
                            ImageUrl = "https://images.unsplash.com/photo-1562771242-a02d9090c90c?auto=format&fit=crop&w=900&q=80",
                            Name = "Elite Training Jersey",
                            Price = 2099m,
                            StockQuantity = 49
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accessories",
                            Description = "Shock-absorbing knee pads with ergonomic contour and breathable knit for volleyball and basketball protection.",
                            ImageUrl = "https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=900&q=80",
                            Name = "All-Court Knee Pads",
                            Price = 849m,
                            StockQuantity = 61
                        },
                        new
                        {
                            Id = 16,
                            Category = "Equipment",
                            Description = "Durable 6-meter speed ladder with adjustable rungs for footwork, acceleration, and conditioning routines.",
                            ImageUrl = "https://images.unsplash.com/photo-1517963628607-235ccdd5476b?auto=format&fit=crop&w=900&q=80",
                            Name = "Agility Speed Ladder",
                            Price = 1149m,
                            StockQuantity = 41
                        },
                        new
                        {
                            Id = 17,
                            Category = "Accessories",
                            Description = "Curved-brim sports cap with sweatband lining, ventilated eyelets, and adjustable back strap for daily wear.",
                            ImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80",
                            Name = "Stadium Cap",
                            Price = 699m,
                            StockQuantity = 68
                        },
                        new
                        {
                            Id = 18,
                            Category = "Shoes",
                            Description = "Stable low-drop training shoes with reinforced heel clip and grippy outsole for lifting and strength sessions.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80",
                            Name = "PowerLift Training Shoes",
                            Price = 4099m,
                            StockQuantity = 23
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
