// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStore.Models;

#nullable disable

namespace SportsStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418150341_AddMoreSampleProductsAndUx")]
    partial class AddMoreSampleProductsAndUx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SportsStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Shoes",
                            Description = "Lightweight running shoes for daily training.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
                            Name = "Air Sprint Running Shoes",
                            Price = 3599m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "Shoes",
                            Description = "High-grip shoes built for quick direction changes.",
                            ImageUrl = "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=900&q=80",
                            Name = "Court Pro Basketball Shoes",
                            Price = 4299m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 3,
                            Category = "Jerseys",
                            Description = "Breathable football jersey with moisture control.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
                            Name = "Metro FC Home Jersey",
                            Price = 2199m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 4,
                            Category = "Jerseys",
                            Description = "Comfort-fit basketball jersey for practice and games.",
                            ImageUrl = "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80",
                            Name = "Tigers Basketball Jersey",
                            Price = 2499m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = 5,
                            Category = "Equipment",
                            Description = "Durable size 5 football for school and club matches.",
                            ImageUrl = "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=900&q=80",
                            Name = "Match Football",
                            Price = 1299m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 6,
                            Category = "Equipment",
                            Description = "Indoor and outdoor basketball with textured grip.",
                            ImageUrl = "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=900&q=80",
                            Name = "Performance Basketball",
                            Price = 1499m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 7,
                            Category = "Equipment",
                            Description = "Set of 20 cones for agility and speed drills.",
                            ImageUrl = "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80",
                            Name = "Training Cones Set",
                            Price = 899m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 8,
                            Category = "Accessories",
                            Description = "Spacious bag with shoe compartment.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
                            Name = "Sports Duffel Bag",
                            Price = 1899m,
                            StockQuantity = 27
                        },
                        new
                        {
                            Id = 9,
                            Category = "Accessories",
                            Description = "Keeps drinks cool during long workouts.",
                            ImageUrl = "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=80",
                            Name = "Insulated Water Bottle",
                            Price = 699m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 10,
                            Category = "Accessories",
                            Description = "Soft and absorbent sweatbands for training.",
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80",
                            Name = "Wrist Sweatbands",
                            Price = 399m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 11,
                            Category = "Accessories",
                            Description = "Goalkeeper gloves with padded palm and strong wrist support.",
                            ImageUrl = "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80",
                            Name = "GripFit Goalkeeper Gloves",
                            Price = 1199m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 12,
                            Category = "Equipment",
                            Description = "Adjustable speed jump rope for cardio and endurance workouts.",
                            ImageUrl = "https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?auto=format&fit=crop&w=900&q=80",
                            Name = "Power Jump Rope",
                            Price = 549m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 13,
                            Category = "Shoes",
                            Description = "Non-marking outsole shoes for indoor court speed and control.",
                            ImageUrl = "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=900&q=80",
                            Name = "Velocity Indoor Futsal Shoes",
                            Price = 3199m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 14,
                            Category = "Jerseys",
                            Description = "Quick-dry training jersey with lightweight mesh panels.",
                            ImageUrl = "https://images.unsplash.com/photo-1562771242-a02d9090c90c?auto=format&fit=crop&w=900&q=80",
                            Name = "Elite Training Jersey",
                            Price = 1999m,
                            StockQuantity = 44
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accessories",
                            Description = "Comfort-fit knee pads for volleyball and basketball sessions.",
                            ImageUrl = "https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=900&q=80",
                            Name = "All-Court Knee Pads",
                            Price = 799m,
                            StockQuantity = 58
                        },
                        new
                        {
                            Id = 16,
                            Category = "Equipment",
                            Description = "Durable footwork ladder for team drills and conditioning.",
                            ImageUrl = "https://images.unsplash.com/photo-1517963628607-235ccdd5476b?auto=format&fit=crop&w=900&q=80",
                            Name = "Agility Speed Ladder",
                            Price = 1099m,
                            StockQuantity = 38
                        },
                        new
                        {
                            Id = 17,
                            Category = "Accessories",
                            Description = "Curved-brim sports cap with breathable fabric.",
                            ImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80",
                            Name = "Stadium Cap",
                            Price = 649m,
                            StockQuantity = 64
                        },
                        new
                        {
                            Id = 18,
                            Category = "Shoes",
                            Description = "Stable sole shoes designed for gym and strength training.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80",
                            Name = "PowerLift Training Shoes",
                            Price = 3899m,
                            StockQuantity = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
